# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliases
export EDITOR="vim"
alias e="mvim --remote-tab-silent 2>/dev/null"
alias "ls"="ls -lG"

# local::lib
[ $SHLVL -eq 1 ] && eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"

# Make DBD::mysql work on OS X
# export DYLD_LIBRARY_PATH="/usr/local/mysql/lib:$DYLD_LIBRARY_PATH"

export LC_ALL=de_DE.UTF-8  
export LANG=de_DE.UTF-8
