# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="blinks"

# Red dots while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Plugins 
plugins=(git)

# Aliases
export EDITOR="vim"
alias e="mvim --remote-tab-silent 2>/dev/null"
alias "ls"="ls -G"

# local::lib
eval `perl -Mlocal::lib=~/perl5`

# Make DBD::mysql work on OS X
export DYLD_LIBRARY_PATH="/usr/local/mysql/lib:$DYLD_LIBRARY_PATH"

# Include local config
if [[ -r ~/.zshrc-local ]]; then
    source ~/.zshrc-local
fi

source $ZSH/oh-my-zsh.sh
